### ISSUE TITLE
Typos & Suggestions

### ISSUE THREAD

**Issue by jwortmann** [TEParsons/Whitelines#1]
Hey, I just saw your scheme in the Package Control repo PRs, and was curious because you used "popup_css". Here are some suggestions:

1. There are some typos in the "globals" keys:
* `find_highight_foreground` should be `find_highlight_foreground`
* `breackets_contents_options` should be `bracket_contents_options`
* `brackets_contents_foreground` should be `bracket_contents_foreground`
* `tags` should be `tags_options`

2. I would recommend to use a color with alpha value for `line_highlight`, so that the background colors from inline diff blocks are not completely hidden.

3. Some of the default build systems (e.g. for Python) will show the position of errors via phantoms. Those phantoms use some undocumented CSS rules which are automatically applied, but only if `popup_css` and `phantom_css` are not set. By using `popup_css` or `phantom_css`, these rules are not applied, which will result in bad style for the phantoms. With some research and trial and error I found the default CSS rules though:
```json
"phantom_css": "body#inline-error{color:color(var(--foreground));background-color:color(var(--background));}a{color:color(var(--bluish));}.error,.deleted{background-color:color(var(--redish) blend(var(--background) 30%));}.success,.inserted{background-color:color(var(--greenish) blend(var(--background) 30%));}.warning,.modified{background-color:color(var(--yellowish) blend(var(--background) 30%));}"
```
You could append this to your own CSS rules if the default style for the inline error phantoms is desired.

**Comment by TEParsons** [comment]
Thanks for the advice! I've made changes now
